name: Minify JS

on:
  push:
    branches: [ main ]

jobs:
  minify:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Auto Minify JS
        uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: "JS"
          output: "min_js"
          
      - name: Auto Minify CSS
        uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: "CSS"
          output: "min_css"
          
      - name: Delete index.html
        uses: JesseTG/rm@v1.0.2
        with:
          path: "index.html"

      - name: Create a copy of index-development.html
        uses: canastro/copy-file-action@master
        with:
          source: "index-development.html"
          target: "index.html"
          
          
          
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: "index.html"
          find: "<title>RockSolid1106</title>"
          replace: "test"
          regex: false
          
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
