name: Minify JS

on:
  push:
    branches: [ development ]

jobs:
  Minify:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Auto Minify JS
        uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: "JS"
          
      - name: Auto Minify CSS
        uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: "CSS"
          
      - name: Auto Minify HTML
        uses: jossydevers/minify-js@v1.0.0
        with: 
          directory: "index.html"
          
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: "main"
          
  
